sudo: false

language: node_js
node_js:
  - '8'
  - '10'
  - '12'
  - '14'

os:
  - linux
  - osx

script:
  - travis_retry npm run test-only

jobs:
  include:
    - stage: other
      script: npm run check
      node_js: lts/*
      name: Check

cache:
  npm: true
  directories:
    - $HOME/.elm
