sudo: false

env:
  matrix:
    - ELM_VERSION=0.16.0 TARGET_NODE_VERSION=node
    - ELM_VERSION=0.16.0 TARGET_NODE_VERSION=0.12
    - ELM_VERSION=0.15.1 TARGET_NODE_VERSION=node
    - ELM_VERSION=0.15.1 TARGET_NODE_VERSION=0.12

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION

script: ./ci.sh
