sudo: false

language: node_js
node_js:
  - '8'
  - '10'
  - '12'

os:
  - linux
  - osx

script:
  - npm run test-only

jobs:
  include:
    - stage: other
      script: npm run format:check
      node_js: lts/*
      name: Lint
