sudo: false

language: node_js
node_js:
    - "node"
    # - "4"

cache:
  directories:
    - test/elm-stuff/build-artifacts
    - sysconfcpus
    - elm19

os:
  - linux
  # - osx

env: ELM_VERSION=0.18.0

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
  - |
    if [ ! -e elm19/elm ];
    then
      mkdir -p elm19
      cd elm19
      curl -O https://44a95588fe4cc47efd96-ec3c2a753a12d2be9f23ba16873acc23.ssl.cf2.rackcdn.com/linux-64.tar.gz
      tar zxvf linux-64.tar.gz
      shasum elm
      cd ..
    fi
  - ls "$(pwd)/elm19"
  - export PATH="$(pwd)/elm19:$PATH"

install:
  - node --version
  - npm --version
  - npm install -g mocha
  # - npm install -g elm@$ELM_VERSION mocha
  # - mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
  # - echo -e "#\!/bin/bash\\n\\necho \"Running elm-make with sysconfcpus -n 2\"\\n\\n$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old \"\$@\"" > $(npm config get prefix)/bin/elm-make
  # - chmod +x $(npm config get prefix)/bin/elm-make
  - npm install

script:
  - npm test
