environment:
  ELM_VERSION: "0.19.0"
  matrix:
  - nodejs_version: "12"
  - nodejs_version: "10"
  - nodejs_version: "8"

platform:
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install
  - start-sleep -s 5 # A five second wait to work around a bug in the elm no-deps installer

test_script:
  - npm test

build: off
